@startuml

skinparam backgroundColor #FFFFFF

' Defines the participants in the protocol
box Client #6897BB
participant "ClientApp" as ClientApp
end box

box Network #FFF68F
participant "NetworkService" as NetworkService
end box

== gRPC GetTargetGlobalPosition ==

' NetworkService thread is running waiting for incoming requests
activate NetworkService
activate ClientApp

' ClientApp requests GetTargetGlobalPosition RPC sending a TargetRequest message
' containing the requesting client ID
ClientApp -> NetworkService: TargetRequest(client_id)

' The RPC request blocks the ClientApp thread while waiting for a response
deactivate ClientApp

' NetworkService receives the RPC request for GetTargetGlobalPosition
' NetworkService has a thread pool for handling asynchronously the requests
' from multiple client, it assigns the request to a worker thread
activate NetworkService

' NetworkService GetTargetGlobalPosition procedure is executed
NetworkService -> NetworkService: Process Request

' The distributed network is active so the target global position is computed
alt Success: is_active=True
    ' The NetworkService sends a TargetResponse message to the ClientApp containing
    ' a positive status for the requested operation and the global coordinates of the target
    NetworkService --> ClientApp : TargetResponse (status: TS_OK, x, y, z)
    activate ClientApp
' The distributed network isn't active so the target global position cannot be computed
else Error: is_active=False
    ' The NetworkService sends a TargetResponse message to the ClientApp containing
    ' a negative status for the requested operation and the global coordinates of the target
    ' set to infinite
    NetworkService --> ClientApp : TargetResponse (status: TS_ERROR, x: inf, y: inf, z: inf)
    deactivate NetworkService
end

@enduml
