@startuml

skinparam backgroundColor #FFFFFF

' Defines the participants in the protocol
box Node #6897BB
participant "NodeStub" as NodeStub
end box

box Network #FFF68F
participant "NetworkService" as NetworkService
end box

== gRPC AddNode ==

' NetworkService thread is running waiting for incoming requests
activate NetworkService
activate NodeStub

' NodeStub requests AddNode RPC sending a NodeRequest message
' containing the requesting node ID, the sensor's position and the bind address
NodeStub -> NetworkService: NodeRequest(node_id, x, y, z, bind_address)

' The RPC request blocks the NodeStub thread while waiting for a response
deactivate NodeStub

' NetworkService receives the RPC request for AddNode
' NetworkService has a thread pool for handling asynchronously the requests
' from multiple client, it assigns the request to a worker thread
activate NetworkService

' NetworkService AddNode procedure is executed
NetworkService -> NetworkService: Process Request

' The distributed network isn't active so the node is added
alt Success: is_active=False
    ' The NetworkService sends a NodeResponse message to the NodeStub containing
    ' a positive status for the requested operation
    NetworkService --> NodeStub : NodeResponse (status: NS_OK)
    activate NodeStub
' The distributed network is active so the node cannot be added
else Error: is_active=True
    ' The NetworkService sends a NodeResponse message to the NodeStub containing
    ' a negative status for the requested operation
    NetworkService --> NodeStub : NodeResponse (status: NS_ERROR)
    deactivate NetworkService
end

@enduml
