@startuml

skinparam backgroundColor #FFFFFF

' Defines the participants in the protocol
box Network #6897BB
participant "NetworkDealer" as NetworkDealer
end box

box Node #FFF68F
participant "NodeRouter" as NodeRouter
end box

== ZeroMQ GetDistance ==

' NodeRouter thread is blocked waiting for incoming requests
' NetworkDelaer thread is running
activate NetworkDealer

' NetworkDealer sends a message to all the nodes in the distributed network
' containing the message GetDistance
NetworkDealer -> NodeRouter: msg(GetDistance)

' NetworkDealer uses a ZeroMQ poller to receive the responses asynchronously
' from all the nodes in the distributed network
activate NetworkDealer

' NodeRouter receives the message containing GetDistance
' NodeRouter thread is unblocked when the message is received
activate NodeRouter

' NodeRouter GetDistance procedure is executed
NodeRouter -> NodeRouter: Process Request

' The NodeRouter sends a message to the NetworkDealer containing the distance
' between the node and the target
' The identity is used to send back to the NetworkDealer the distance
NodeRouter --> NetworkDealer : msg(identity:distance)
deactivate NodeRouter
deactivate NetworkDealer

@enduml
